// KLOSTERBINGO 2026 - 125 bingokort
const CARDS = [
  "Anarththan får kjæreste",
  "Hans til å knulle",
  "Odin til å Knulle",
  "Odin spyr utenfor do",
  "En av gutta i klassen kysser Mina",
  "Mina gråter (Forran oss)",
  "Anar knuller 07",
  "Toby dick pick i gruppechat",
  "Gutta vors i klosteret uten oss",
  "En av gutta får med seg et «dyr» hjem",
  "Noen ser Mohand",
  "Tørres får kjæreste",
  "Odin tar bilde av en av gutta in action",
  "Oskar i «Fight»",
  "Christian Borch deep talk",
  "Christian Borch spotta med kamera",
  "Jonathan spyr",
  "Mika spyr",
  "Felix får noen til å gråte",
  "En av gutta kysser en FEIT dame",
  "Rithi slåsskamp",
  "Viktor på DT",
  "En av gutta blir slått ned",
  "Augoga ggåter",
  "Felix spyr i vasken",
  "Andrea sover på sofaen igjen",
  "Kaisa på DT",
  "Caro flasher",
  "En geek fyllamelding",
  "Klassenasch minst(1 jente i klassen)",
  "Felix tar med en jente i klassen på nasch",
  "Anar to vinflasker",
  "Anar ølshotglas",
  "Olav(stor) får på",
  "Klosternasch til etter 4:30",
  "Klasseincest",
  "En bro spyr på bedpress",
  "Toby får seg noe",
  "Noen tar taxi",
  "Anar blir kasta ut",
  "En bro glemmer legitimasjon",
  "Hans bæsjer på vors",
  "En bro kysser dame 27+",
  "Tørres spyr på labamba",
  "Alle gutta jobb før jul",
  "Hans kysser en gutt",
  "Kurdin snap i klassechat",
  "Anar sovner i klosteret",
  "Toby kler av seg (Forran huzzen)",
  "Toby blir rejecta av en abakuse",
  "Abakuse spyr på vors",
  "Leon sixpack før jul",
  "Adam sixpack før jul",
  "Karin abakusincest",
  "Ingrid til å spy",
  "Noen knekker noe",
  "Noen i polititrøbbel",
  "Fellesvors med gutta på tvers",
  "En av gutta får på på Samf",
  "Anar bruker 1000kr + på en dag på byen",
  "Noen spyr av beerio kart",
  "Jente på beeriokart",
  "Anar kysser to jenter på en kveld",
  "En bro sovner i grøfta",
  "En bro tar en firedager",
  "Toby til å knuller",
  "En bro får på med en østasian",
  "En bro får på med en araber + nordafrika",
  "En bro får på med en utveklsingstudent",
  "En geit får minst 2 Aer",
  "Ingen av økadgutta stryker",
  "En bro på legevakta fra fylla",
  "Anar benker 115 kg",
  "Toby benker 110 kg",
  "En bro må skifte på vors",
  "Odin kysser en jente på byen",
  "Bodø Glimt vinner en CL kamp",
  "Viking vinner en CL kamp",
  "En abakuse til å si baka",
  "Horehuset til å ha en utflytting",
  "Horehuset til å bryte seg inn for nasch",
  "Felix til å komme i en forelesning",
  "Anar over 3,5 jenter på dates i år",
  "Anar sovner på vors",
  "En bro får på med en datajente",
  "En av gutta sipper ice på vors",
  "Mudryk mål",
  "Garnacho mål",
  "En bro kjøper over 1,5 enheter til jente på byen",
  "En bro får på med en ginger",
  "En bro får en STD",
  "Lea på DT",
  "Tottenham nedre 14 til jul",
  "En bro mister mobilen på byen",
  "Spotter en dverg på byen",
  "En bro drar på Tempo Torsdag",
  "En bro drar på Sprudle Søndag",
  "Maria på byen",
  "En bro skinner/kort buzz",
  "En bro (– Toby) tar melkoshima",
  "Vi spotter en fra VGS",
  "Kjendis på byen",
  "Fredrikk (Utleier) på byen",
  "Spotter noen i itDAGENE merch utenfor hjemmet",
  "En bro går 500kr pluss på norsk tipping",
  "Hans nusser over 1,5 damer på en kveld",
  "Ny leder av israel",
  "Trump besøker Grønland",
  "Hans til å si Baka",
  "Toby melder seg på Åre",
  "Rapportert ebolacase i Sentralafrikanske republikk",
  "En bro blir icet tre ganger på en kveld",
  "Tørres spot på DT",
  "Vi møter en jøde",
  "Olav (Bratsvedal) til å få jobb",
  "En ikke Anarbro/søster overnatter på sofaen",
  "Over 2,5 vors/fester i Anarkollektivet",
  "Vors hos Toby",
  "Olav spyr",
  "Over 6,5 drikkebonger på et arrangement",
  "En bro (-Anar) får dame",
  "Hans skjeller ut en jente til trynet hennes",
  "Stol knekker på vors",
  "En do blir tetta (Vi er passivt/aktivt innvolvert)",
  "En bro legger ut larp på linkedIN",
];

if (typeof module !== "undefined") {
  module.exports = CARDS;
}
